[package]
name = "sharded_sqlite"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
hashing = { path = "../hashing" }
log = { workspace = true }
rusqlite = { version = "0.37.0", features = ["bundled"] }
tokio = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
sharded_lmdb = { path = "../sharded_lmdb" }
task_executor = { path = "../task_executor" }
tempfile = { workspace = true }
testutil = { path = "../testutil" }
tokio = { workspace = true, features = ["rt", "macros"] }

[[bench]]
name = "backend_comparison"
harness = false
